[Task#6386] Initial Project
awesome-academy/i-oe14-weather pull request #3
Opened 2019-02-14 09:57 UTC by minhduc2511

## [Pull request title]
Initial Project

### [Redmine link]
https://edu-redmine.framgia.vn/issues/6386

2019-02-14 10:19 UTC, tgdong2296 approved these changes

2019-02-14 10:33 UTC, hung070996 commented on Weather/Weather/Controllers/ViewController.swift
> +
thừa

2019-02-14 10:33 UTC, hung070996 commented on Weather/Weather/Resources/AppDelegate.swift
> +
thừa

2019-02-14 10:33 UTC, hung070996 commented on Weather/Weather/Resources/AppDelegate.swift
> +    func applicationWillResignActive(_ application: UIApplication) {
bỏ các hàm ko dùng

2019-02-14 13:13 UTC, tienpx3010 commented on Weather/Podfile
> +pod 'ObjectMapper', '~> 3.4'
```suggestion
     pod 'ObjectMapper', '~> 3.4'
```

2019-02-14 13:14 UTC, tienpx3010 commented on Weather/Weather/Resources/AppDelegate.swift
> +
thừa dòng

2019-02-14 13:15 UTC, tienpx3010 commented on Weather/Weather/Resources/AppDelegate.swift
> +        self.saveContext()
```suggestion
        saveContext()
```

2019-02-15 01:52 UTC, longvt96 approved these changes

2019-02-15 01:59 UTC, tgdong2296 approved these changes

2019-02-15 02:07 UTC, tienpx3010 commented on .gitignore
> +Movie/Utils/APIKey.swift
Xoá đi

2019-02-15 02:07 UTC, tienpx3010 commented on Weather/Weather/Resources/AppDelegate.swift
> +
Thừa dòng

2019-02-15 02:07 UTC, tienpx3010 commented on Weather/Weather/Resources/AppDelegate.swift
> +
Thừa dòng

2019-02-15 02:24 UTC, tienpx3010 approved these changes

2019-02-15 02:30 UTC, hung070996 approved these changes

2019-02-15 02:31 UTC, cuongvx-0845 requested changes

2019-02-15 02:31 UTC, cuongvx-0845 commented on Weather/Weather/Resources/AppDelegate.swift
> +
Thừa dòng nè

2019-02-15 02:31 UTC, merged